openapi: 3.1.0
info:
    title: 간단한 계산기
    description: 이 프로젝트는 Layered Architecture를 기반으로 한 간단한 사칙연산 계산기 API 를 개발하는 과제입니다.
    version: 1.0.0
servers:
    - url: 'https://api.wild-backend.com/v1'
paths:
    /calculations:
        post:
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                number1:
                                    type: number
                                    description: 첫번째 number 인수
                                    example: 1
                                number2:
                                    type: number
                                    description: 두번째 number 인수
                                operations:
                                    type: string
                                    description: 사칙연산("+", "-", "*", "/")
                                    example: "+"
            responses:
                200:
                    description: 연산 결과
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    result:
                                        type: number
                                        description: 계산 결과값
                                        example: 3
                400:
                    description: 사칙연산 기호가 올바르지 않습니다.
        get:
            responses:
                200:
                    description: 연산 계산 모음집
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    calculations:
                                        type: array
                                        items:
                                            type: object
                                            properties:
                                                number1:
                                                    type: number
                                                    example: 1
                                                number2:
                                                    type: number
                                                    example: 2
                                                operations:
                                                    type: string
                                                    example: "+"
                                                result:
                                                    type: number
                                                    example: 3
